AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: hackeroni-slack-disclosure-bot
Parameters:
  SlackWebhookURL:
    Type: String
    Description: The URL of the Slack Incoming Webhook
Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: True
      QueueName: hacktivity.fifo
  PollFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./poll/
      Handler: lambda.lambda_handler
      FunctionName: hacktivity-poll
      Runtime: python3.9
      Architectures:
        - arm64
      Timeout: 15
      Tracing: Active
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Policies:
      - SQSSendMessagePolicy:
          QueueName:
            !GetAtt Queue.QueueName
      Environment:
        Variables:
          SQS_QUEUE: !Ref Queue
  SlackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./slack/
      Handler: lambda.lambda_handler
      FunctionName: hacktivity-slack
      Runtime: python3.9
      Architectures:
        - arm64
      Timeout: 15
      Tracing: Active
      Events:
        Queue:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue.Arn
            FunctionResponseTypes:
            - ReportBatchItemFailures
      Policies:
      - SQSPollerPolicy:
          QueueName:
            !GetAtt Queue.QueueName
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !Ref SlackWebhookURL
Outputs:
  QueueARN:
    Value: !GetAtt Queue.Arn
  PollARN:
    Value: !GetAtt PollFunction.Arn
  SlackARN:
    Value: !GetAtt SlackFunction.Arn
